### PR TITLE
v1.7.0

### PR DESCRIPTION
**Pull request by joyeecheung**
Need to use my windows machine to test it out before releasing it.

### CODE REVIEW

**Comment by targos** [comment]
I am on Windows. What should I test?

**Comment by joyeecheung** [comment]
@targos Using the master to `get-metadata` a PR  and see if the CLI has been broken should be enough, thanks!

**Comment by targos** [comment]
Output:
image

**Comment by joyeecheung** [comment]
@targos Looks good. Thanks!

**Pull request merged**
