### PR TITLE
feat: add releaseDate to json

### PR DESCRIPTION
**Pull request by marco-ippolito**
Fixes: https://github.com/nodejs-private/security-release/issues/23

@RafaelGSS

### CODE REVIEW

**Review by RafaelGSS — APPROVED** [review]

**Review by RafaelGSS — COMMENTED** [review]
actually, we need to check if a valid date is given, if not it should leave it empty. For instance, `TBD`.

**Comment by marco-ippolito** [comment]
> actually, we need to check if a valid date is given, if not it should leave it empty. For instance, `TBD`.
if invalid date is given it will throw right now

**Comment by RafaelGSS** [comment]
> > actually, we need to check if a valid date is given, if not it should leave it empty. For instance, `TBD`.
> 
> if invalid date is given it will throw right now

But, what if we don't have a target date? I would like to pass TBD

**Comment by marco-ippolito** [comment]
ok so I'll validate only if different from 'TBD'

**Review by RafaelGSS — APPROVED** [review]

**Pull request merged**
