### PR TITLE
git-node: implement "rebase" & "continue" options for "land" command

### PR DESCRIPTION
**Pull request by BeniCheni**
Refs: #229 

###### Local Test

```
→ git node land --rebase  
Successfully rebased and updated refs/heads/master.
   ✔  Rebased current branch
```

```
→ git node land --continue
Running `git rebase --continue`..
Successfully rebased and updated refs/heads/master.
```

### CODE REVIEW

**Comment by joyeecheung** [comment]
Thanks for the PR!

I need to take a moment to think about the implications to the workflow..

**Comment by BeniCheni** [comment]
Hello, reviewer(s),

Trying to follow up with this pending PR. Please let me know if this PR does not fit the workflow of `node-core-utils`, or it needs changes. I'll be happy to close it, or update it respectively.

**Comment by codebytere** [comment]
I believe rebasing happens automatically as part of the workflow now - so i think this can be closed (cc @joyeecheung can you confirm?)

**Comment by BridgeAR** [comment]
That does indeed seem to. Closing as resolved. Thanks a lot for the contribution nevertheless!

**Pull request closed without merging**
