### PR TITLE
change rejected to requested changes

### PR DESCRIPTION
**Pull request by devsnek**
Rejected isn't really very accurate and it has a negative connotation when in reality its more likely that the reviewer wants the PR to land, but wants to make it better (hence "requested changes")

### CODE REVIEW

**Comment by devsnek** [comment]
how about we consider empty request changes as rejection

**Comment by Tiriel** [comment]
Don't know if it's this simple. We could also parse comments for `:-1:` but I don't know if it's a viable condition.

But that's just my two cents anyway, as said, if the majority thinks we should make the change, then go.

**Comment by joyeecheung** [comment]
CI looks green: https://travis-ci.org/nodejs/node-core-utils/builds/301478072

**Comment by refack** [comment]
@Tiriel I'm not sure that is completely correct, as the status of a fully "rejected" PR will be `Closed`. As long as the PR is open it is either still in negotiations, or `blocked` by some other issue.
The semantic of the GitHub ❌ has been debated is several issues (mainly https://github.com/nodejs/CTC/issues/128) but AFAICT it wasn't used to indicate a "reject" status. I'm not even sure node core needs a "reject" status...

If at some point we develop an abandoned-issue-closing-bot, then we might consider a PR with a ❌ for closure...

**Comment by Tiriel** [comment]
@refack Well that's precisely my point, it's not used solely for requesting change, nore purely for rejection.
Of course it doesn't mean the issue has been definitely rejected, but you can't deny some people (and quite often from what I've seen) use it to say they feel the feature/change isn't a good one and should be abandonned.

So, while I think the current workflow can be perfected, I don't think we should completely strip away the "rejection" part.

**Comment by refack** [comment]
> So, while I think the current workflow can be perfected, I don't think we should completely strip away the "rejection" part.

I _think_ we should. Mainly for "optics".
As far as I remember the term "rejected" is never used in node's governance model, but rather the term "blocked", as in any Collaborator can block, but that can be overridden either for lacking explanation, or by the TSC.


> you can't deny some people (and quite often from what I've seen) use it to say they feel the feature/change isn't a good one and should be abandonned

I don't deny it, but I do think it's the minority, and it's sort of a bug in the process. Optimally the ❌ review should be used exclusively to request changes, while full-on rejection should be done in words.

Again this is non-trivial issue, but I do feel this tool should be non-opinionated, and hance should not assume intent. A ❌ review is called "Request Changes" by GitHub, and we should follow suit:
image

**Comment by Tiriel** [comment]
@refack Thanks for taking the time in any case.

It does make sense indeed, and for consistency I agree there's a case in changing the workflow. This does let me with the impression that there's a point t o consider about full on rejections and that there should be handled though, even in minority.

Just dismissed my review so the PR can be merged clean :)

**Comment by cPhost** [comment]
Merging it now since minor changes and approved.

**Pull request merged**
