### PR TITLE
Git node status

### PR DESCRIPTION
**Pull request by GithubGoldMiner**
This commit is related to #228 , if solution is in the right direction, I will then add tests accordingly. :)

### CODE REVIEW

**Comment by joyeecheung** [comment]
Thanks for picking this up. Although I am afraid logging the JSON out probably is going to be quite  confusing to users who don't really understand the structure of it..git-node currently also tries to serialize the access token there, which makes the output even more weird. I think some textual output generating from the `state`, `prid`, `config.upstream`, `config.branch` would be better, although I don't quite remember what the possible combinations are without digging into that part of the code base.

**Comment by GithubGoldMiner** [comment]
@joyeecheung Yes I agree with your concern. I will look more into that part of the codebase to find a more proper solution and modify my pr. Thank you so much for your valuable response!

**Comment by GithubGoldMiner** [comment]
@joyeecheung Hi, I am wondering, for `git node status`. We just need to display `state`, `prid`, `config.upstream` and `config.branch` in a meaningful way?

**Comment by joyeecheung** [comment]
@GithubGoldMiner That would be a good start. The information in the config can be useful as well. Also it would be nice to display additional state of git if it’s in the middle of a git am or git rebase (no docs for that but we have code relying on some special files created by git for state management

**Comment by GithubGoldMiner** [comment]
@joyeecheung Absolutely! I will look into those in the codebase and commit soon! Thank you!

**Comment by codebytere** [comment]
@GithubGoldMiner would you still want to work on this or can it be closed?

**Comment by codebytere** [comment]
Closing as outdated/abandoned. If someone wishes to pick this up again, please reopen/leave a message!

**Pull request closed without merging**
