### PR TITLE
chore(test): migrate to `node:test`

### PR DESCRIPTION
**Pull request by aduh95**

### CODE REVIEW

**Comment by targos** [comment]
`Segmentation fault (core dumped)`

Interesting.

**Comment by MoLow** [comment]
> Probably related to https://github.com/nodejs/node/pull/46674
I am pretty sure it is since node 16 is lacking many features of the test runner

**Comment by MoLow** [comment]
I was able to run on all three node versions in my branch:
https://github.com/aduh95/node-core-utils/compare/node--test...MoLow:node-core-utils:node--test
the main 2 issues that are not supported on node 16 are 
https://github.com/nodejs/node/pull/45055
https://github.com/nodejs/node/pull/45161

**Comment by MoLow** [comment]
@aduh95 the tests pass but coverage can only be collected on node >= 18

**Comment by MoLow** [comment]
I think it might be a fair mitigation to run tests without coverage on node 16

**Comment by aduh95** [comment]
It looks like there are a few test failures though

**Comment by MoLow** [comment]
yeah since `node --test` now runs files inside `test/fixtures`, I think running `test-unit` would have the same outcome as running `test-all` had before, unless I am missing something

**Comment by MoLow** [comment]
@aduh95 this should work: https://github.com/aduh95/node-core-utils/commit/d7ea450b4f5612d5508920aee953960602481977

**Comment by aduh95** [comment]
For some reason, CI picks up v18.15.0 only on Windows 🤔

**Comment by MoLow** [comment]
@aduh95 seems like `actions/setup-node@v3` should have `check-latest: true`

**Review by MoLow — APPROVED** [review]
🎉

**Comment by MoLow** [comment]
@aduh95 this requires amending the commit message(s)

**Comment by aduh95** [comment]
No it doesn't, the title of the PR (which is what GitHub uses as the default commit message) is complying with Conventional Commit spec.

**Comment by MoLow** [comment]
so this check should be fixed to only look at the PR name? https://github.com/nodejs/node-core-utils/actions/runs/4430791079/jobs/7772963001?pr=670

**Comment by aduh95** [comment]
The issue is that some PR are being "Rebase and merge"d, in which case it makes sense to check every commits.

**Review by targos — APPROVED** [review]

**Pull request merged**
