### PR TITLE
chore!: switch to `@node-core` scope

### PR DESCRIPTION
**Pull request by aduh95**
Not sure this is ready yet, we may need a new NPM_TOKEN on the repo secret.

Refs: https://github.com/nodejs/TSC/issues/1178

### CODE REVIEW

**Comment by MoLow** [comment]
we should probably also publish one last version to https://www.npmjs.com/package/node-core-utils with a output/warning saying it moved

**Comment by aduh95** [comment]
> we should probably also publish one last version to https://www.npmjs.com/package/node-core-utils with a output/warning saying it moved

I think we can `npm deprecate` it without publishing a new version.

**Comment by targos** [comment]
The current NPM_TOKEN should work. I can replace it with a granular one when the package exists on npm.

**Review by MoLow — DISMISSED** [review]

**Comment by targos** [comment]
release-please workflow needs an update as well.

**Review by targos — APPROVED** [review]

**Review by MoLow — APPROVED** [review]

**Review by VoltrexKeyva — APPROVED** [review]

**Pull request merged**
