### PR TITLE
fix: potential non-url Fixes being added to metadata

### PR DESCRIPTION
**Pull request by codebytere**
Closes https://github.com/nodejs/node-core-utils/issues/233.

Filters out anything from being added to `Fixes` metadata that does not look e.g like:

Fixes #16
Fixes nodejs/build#1961
Fixes https://github.com/nodejs/node/issue/12345

### CODE REVIEW

**Comment by richardlau** [comment]
Would it still allow URLs?

**Comment by joyeecheung** [comment]
From what I can tell this would make links like `Fixes: https://github.com/nodejs/node/issue/12345` invalid?

**Comment by codebytere** [comment]
Missed a spot in the regex - should be fixed up now!

**Comment by mmarchini** [comment]
The goal lgtm, would need more time to review the regex (if others think the regex is fine I'm good with it too!)

**Comment by richardlau** [comment]
Tests would be good. Particularly one showing an example of a non-url Fixes being ignored and one showing a Fixes with a full URL is accepted.

**Pull request closed without merging**
