### PR TITLE
git-node: execute local core-validate-commit

### PR DESCRIPTION
**Pull request by targos**
Fixes: https://github.com/nodejs/node-core-utils/issues/191

### CODE REVIEW

**Comment by joyeecheung** [comment]
Shouldn't we check for Windows and run `npx.cmd` instead?

**Comment by targos** [comment]
I'm not convinced using npx is a good thing.

**Comment by devsnek** [comment]
the thing that stands out to me is that npx has a lot of side-effects including installing packages/running package scripts which seems fairly undesirable

**Comment by cPhost** [comment]
Thanks @targos for the fix. 
Although i was also wondering from last PR did npx installed `core-validate-commit` into node's directory since `git-node` is ran on node's directory?

And other thing that weird is what `npx` did not work since in Window 10 at-least you don't need to type out the whole `npx.cmd` to it for it work?

**Pull request merged**
