### PR TITLE
Testing github intergrations

### PR DESCRIPTION
**Pull request by joyeecheung**
This PR is for testing how we can bring the CI integrations back without granting third-party access to those services..

### CODE REVIEW

**Comment by joyeecheung** [comment]
So..

* [Travis builds](https://travis-ci.org/nodejs/node-core-utils)
* [Appveyor builds](https://ci.appveyor.com/project/joyeecheung/node-core-utils)  under joyeecheung/node-core-utils even though it's pulling code from this repo
* [Code cov is reported](https://codecov.io/gh/nodejs/node-core-utils)

...(no idea how to bring snyk back)

but only the code-cov is able to report status to github?

**Comment by Tiriel** [comment]
It may be a dumb question (you'll notice I have plenty of those), but isn't that precisely the purpose of the [github-bot](https://github.com/nodejs/github-bot) ?

The readme isn't that clear, but it seems to indicate it can be used to display travis reports.

**Comment by joyeecheung** [comment]
Progress: we need to use the github bot of the organization to post build status now, since we don't allow any third-party access to the nodejs organization except our own bots.

Refs: https://github.com/nodejs/nodejs.org/issues/355
Refs: https://github.com/nodejs/citgm/issues/102
Refs: https://github.com/nodejs/github-bot/blob/master/scripts/display-travis-status.js

Before I got the bot hooked into this repo we will need to go see the Travis & Appveyor status ourselves in https://travis-ci.org/nodejs/node-core-utils and https://ci.appveyor.com/project/joyeecheung/node-core-utils

**Comment by joyeecheung** [comment]
PR opened in https://github.com/nodejs/github-bot/pull/156

**Comment by Tiriel** [comment]
Wasn't a dumb question after all then :smile: 

Awesome work!

**Comment by joyeecheung** [comment]
Uh, that's weird, the github bot deployed on my own server with my own token can update the status of this PR, but the github bot deployed in the foundation's server got 404 when it tries to `pull_request.synchronize`..

**Comment by joyeecheung** [comment]
Ah, I think I've got this working!

**Comment by joyeecheung** [comment]
Yes, it's working properly now. Next step is to implement the appveyor couterpart

**Comment by joyeecheung** [comment]
I am going to close this and open another one when I started implementing appveyor scripts

**Pull request closed without merging**
