### PR TITLE
chore: update release-please config

### PR DESCRIPTION
**Pull request by targos**
- Use new repository for the action
- Use nodejs-github-bot's PAT
- Set minimal permissions for the default token

### CODE REVIEW

**Review by aduh95 — APPROVED** [review]
We could also set explicitly `permissions: contents: read` since that's the only needed permission required from now on IIUC

**Comment by targos** [comment]
According to the docs, it needs write permission: https://github.com/googleapis/release-please-action#workflow-permissions

**Comment by aduh95** [comment]
> According to the docs, it needs write permission: https://github.com/googleapis/release-please-action#workflow-permissions

Setting `permissions: contents: read` only affects permission of the `GITHUB_TOKEN`, which is only used by `actions/checkout` after this PR. The required permissions for `googleapis/release-please-action` are irrelevant, because it uses a different token IIUC.

**Comment by targos** [comment]
I see. Updated, thanks!

**Comment by aduh95** [comment]
`RequestError [HttpError]: Error creating Pull Request: Resource not accessible by personal access token` 🤔

**Comment by targos** [comment]
I might have given the wrong permission. Will check when I'm on my computer unless someone else does it first

**Comment by targos** [comment]
https://github.com/settings/personal-access-tokens/3911092

CleanShot 2024-09-01 at 19 33 40@2x

**Comment by targos** [comment]
I forgot to give write access to the bot in https://github.com/nodejs/node-core-utils/settings/access. Now it's done.

**Pull request merged**
