### PR TITLE
refactor: use inquirer to implement CLI.prompt

### PR DESCRIPTION
**Pull request by targos**

### CODE REVIEW

**Comment by targos** [comment]
@joyeecheung Probably. I'll try it in another PR.

**Comment by targos** [comment]
@joyeecheung I see that `cli.promptForInput` is not used at all. Should I just remove it?

**Comment by targos** [comment]
I opened https://github.com/nodejs/node-core-utils/pull/315

**Comment by refack** [comment]
It was a preliminary for https://github.com/nodejs/node-core-utils/pull/299

**Pull request merged**
