### PR TITLE
lib: add request-v3, for GitHub API v3 support

### PR DESCRIPTION
**Pull request by cPhost**
We can use this whenever we need it. Let me know if you think there should a diffrent name for this.

### CODE REVIEW

**Comment by targos** [comment]
I think we should use a library like https://github.com/octokit/node-github (it supports promises) for API v3 calls.

**Comment by cPhost** [comment]
@targos that would be good idea if this whole repo was on v3 but it based on v4 it just required for one functionality or maybe some in feature.

**Comment by apapirovski** [comment]
I think... I tend to agree with @targos here. Using `node-github` means we don't need to worry about testing some of that stuff and it allows us to easily expand functionality in the future, as opposed to refactoring everything when we suddenly need it at a later time.

**Comment by Tiriel** [comment]
I do agree too. For now we need only for one thing, but I think we're doomed to have more uses for it later unless GitHub implements new nodes in the Graph API.

I think adding the `node-github` package would be a safe bet now.

**Comment by joyeecheung** [comment]
A few thoughts:

1. We can just put a v3 method/property on the `Request` class in `lib/request.js`.
2. I tend to agree with @targos , we can instantiate the node-github client in `Request` and expose it as `request.v3`

**Pull request closed without merging**
