### PR TITLE
[WIP] git-hooks: add ncu-git-hooks to install pre-commit hook

### PR DESCRIPTION
**Pull request by priyank-p**
This still needs some work on some parts of code but mostly is ready. Also needs docs and perhaps tests.

Basic Way to use:
```bash
ncu-git-hooks install <hook>
```

And after that, it should run `./configure && make -j4 test` on Unix while `vcbuild test` on windows when you make a commit. It should also work on windows, if not we can use PowerShell later.

### CODE REVIEW

**Comment by joyeecheung** [comment]
Thanks for picking this up!

> And after that, it should run ./configure && make -j4 test on Unix while vcbuild test on windows when you make a commit. 

I don't think that's what most people do though? Also I've seen many people developing on a local branch or in their own fork before submitting a PR and the code there is usually not ready for a full test before it gets out of WIP.

**Comment by cPhost** [comment]
That makes `pre-commit` easier then, so it would be just `make lint` or `vcbuild lint`.

**Comment by cPhost** [comment]
Currently works like this:
git-hooks

**Comment by joyeecheung** [comment]
@cPhost From what I can tell most people would not want running linters on commit in their workflow, which is why ‘make test-only’ exists. Mind that commit is not reserved for changes that will be summitted right away, a lot of times it’s just about checking WIP code into the source control but at that point you don’t really care about linters or tests since it is just a WIP.

**Comment by cPhost** [comment]
So we want to run `make test-only` for each commit instead of linter or test?

It looks like the workflow of node is quite not the same as other projects, which is because in the PR mostly some commit are not standalone sometimes and so they are squashed into one while landing.

Is it that we don't need `pre-commit`? I used it because was pretty easy to do than `pre-push` where we would need to get commit hash of each commit made and send it through `core-validate-commit`. (+ some more things to consider too. so didn't quite want to take it just yet).

**Comment by joyeecheung** [comment]
The primary reason I would say is that `make test` takes a lot time to run, especially when you are switching between branches and need to recompile. Also yes because node takes the git commit history seriously and most of the times the commits should be able to pass standalone.

**Comment by joyeecheung** [comment]
> So we want to run make test-only for each commit instead of linter or test?

IMO nothing should be done in the pre-commit hooks. The ideal would be to only run those things when they are being pushed to a branch with PR opened.

**Comment by cPhost** [comment]
OK, makes sense, I will start implementing `pre-push` hook then.

**Comment by codebytere** [comment]
Can this be closed?

**Comment by priyank-p** [comment]
I will close this out!

**Pull request closed without merging**
