### PR TITLE
git-node v8: prompt on merge conflict

### PR DESCRIPTION
**Pull request by hashseed**
Instead of performing `git apply` and aborting if it fails (which happens often), perform `patch -p1 --merge` instead to produce merge artifacts and then prompt for user input to continue.

It should look something like this:

example output

### CODE REVIEW

**Comment by hashseed** [comment]
This fixes https://github.com/nodejs/node-core-utils/issues/303

**Comment by targos** [comment]
Nice, thank you! I tested it locally and it works :+1:

**Comment by targos** [comment]
I will follow up with another PR that uses "backport" instead of "cherry-pick" in the commit message when a conflict occurs, but after https://github.com/nodejs/node-core-utils/pull/304 is landed.

**Comment by hashseed** [comment]
I don't actually have power to merge this :)

**Comment by targos** [comment]
I do ;)

**Pull request merged**
