### PR TITLE
feat: spawn the user's editor to edit commit messages

### PR DESCRIPTION
**Pull request by targos**

### CODE REVIEW

**Comment by targos** [comment]
Ping. I'd be really happy to have this feature :)

**Review by Trott — APPROVED** [review]
Code looks fine to me, but I didn't test it. Speaking of which, would it make sense to add tests for these options?

**Comment by joyeecheung** [comment]
> Speaking of which, would it make sense to add tests for these options?

I think we'd have to create some kind of infra for testing git node in general first - testing silent runs with --yes would be easier but testing interactive runs like this one requires would be difficult. 

Speaking of which..have you tried running this with --yes and --autorebase? @targos

**Comment by targos** [comment]
> Speaking of which..have you tried running this with --yes and --autorebase?

Yes, no problem with those options.

**Review by aduh95 — APPROVED** [review]

**Pull request merged**
