### PR TITLE
request: user-friendly error rather than error json

### PR DESCRIPTION
**Pull request by cPhost**
Fixes: #120

### CODE REVIEW

**Comment by cPhost** [comment]
@Tiriel  sure.
```bash
$ get-metadata 163754
✖ Getting commits from nodejs/node/pull/163754
✖  [NOT_FOUND] GraphQL request Error: Could not resolve to a PullRequest with the number of 163754.
Error: [NOT_FOUND] GraphQL request Error: Could not resolve to a PullRequest with the number of 163754.
    at Request.request (/home/ubuntu/workspace/node-core-utils/lib/request.js:51:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
{
  "variables": {
    "after": null,
    "prid": 163754,
    "owner": "nodejs",
    "repo": "node"
  }
}
```

**Comment by targos** [comment]
This looks much better as a generic output, thanks!

I had in mind the idea to detect this specific error and print a custom message but that can be done independently.

**Comment by cPhost** [comment]
Yes, we can add custom error message but for that have to look into documentation more. Will attempt to do that.

**Comment by joyeecheung** [comment]
CIs are happy, going to merge this

**Pull request merged**
