### PR TITLE
chore!: remove unmarked DEP0XXX handler

### PR DESCRIPTION
**Pull request by aduh95**
The deprecation numbers are linted by the `test-doc` test suite, and using `DEP0XXX` would be flagged as invalid before the PR can land.

### CODE REVIEW

**Comment by richardlau** [comment]
> The deprecation numbers are linted by the `test-doc` test suite, and using `DEP0XXX` would be flagged as invalid before the PR can land.

Is that true on all supported release lines?

**Comment by aduh95** [comment]
> > The deprecation numbers are linted by the `test-doc` test suite, and using `DEP0XXX` would be flagged as invalid before the PR can land.
> 
> Is that true on all supported release lines?

It seems that https://github.com/nodejs/node/pull/41992 hasn't been backported to v14.x, so I guess this should wait for v14.x to be officially EOL.

**Comment by richardlau** [comment]
> > > The deprecation numbers are linted by the `test-doc` test suite, and using `DEP0XXX` would be flagged as invalid before the PR can land.
> > 
> > 
> > Is that true on all supported release lines?
> 
> It seems that [nodejs/node#41992](https://github.com/nodejs/node/pull/41992) hasn't been backported to v14.x, so I guess this should wait for v14.x to be officially EOL.

Thank you for checking. I suspect it's highly unlikely we'll deprecate something new in Node.js 14 before it reaches End-of-Life. I'd be okay landing if other @nodejs/releasers agree, otherwise we can wait.

**Comment by targos** [comment]
SGTM

**Review by RafaelGSS — APPROVED** [review]

**Review by juanarbol — APPROVED** [review]
LGTM

**Review by BethGriggs — APPROVED** [review]

**Review by richardlau — APPROVED** [review]

**Comment by targos** [comment]
@aduh95 there's a conflict now.

**Pull request merged**
