### PR TITLE
feat: enable parsing citgm-nobuild jobs

### PR DESCRIPTION
**Pull request by codebytere**
Refs https://github.com/nodejs/node-core-utils/pull/454.

Extends `ncu-ci citgm` by allowing for users to also check `citgm-smoker-nobuild` jobs.  To specify that a job is a `nobuild` job, one would run:

```shell
ncu-ci citgm 866 --nobuild
```

Output:
```
Developer ❯ ncu-ci citgm 866 --nobuild                                          9:36AM
--------------------------------------------------------------------------------
[1/1] Running CITGM: 866
--------------------------------------------------------------------------------
✔  Summary data downloaded
✔  Results data downloaded
----------------------------------- Summary ------------------------------------
Result     FAILURE
URL        https://ci.nodejs.org/job/citgm-smoker-nobuild/866/
Source     
Commit     Unknown
Date       
Author     Unknown
---------------------------------- Statistics ----------------------------------
┌─────────┬────────┐
│ (index) │ Values │
├─────────┼────────┤
│ Failed  │   3    │
│ Skipped │   0    │
│ Passed  │   9    │
│  Total  │   12   │
└─────────┴────────┘
----------------------------------- Failures -----------------------------------
┌────────────────────────┬───────────────────┐
│        (index)         │         0         │
├────────────────────────┼───────────────────┤
│        osx1015         │                   │
│     win2016-vs2017     │ 'through2-v4.0.2' │
│ fedora-last-latest-x64 │                   │
│       debian9-64       │                   │
│     ubuntu1804-64      │                   │
│      rhel7-s390x       │                   │
│      aix71-ppc64       │ 'through2-v4.0.2' │
│        osx1014         │                   │
│      win10-vs2019      │ 'through2-v4.0.2' │
│   fedora-latest-x64    │                   │
│     centos7-ppcle      │                   │
│     ubuntu1604-64      │                   │
└────────────────────────┴───────────────────┘
```

<details>
<Summary> JSON Output </Summary>

```json
{
  "upstream": "https://ci.nodejs.org/job/citgm-smoker-nobuild/866/",
  "passed": 9,
  "total": 12,
  "skipped": 0,
  "failed": 3,
  "osx1015": {
    "url": "https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=osx1015/866/",
    "modules": []
  },
  "win2016-vs2017": {
    "url": "https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=win2016-vs2017/866/",
    "modules": [
      {
        "name": "through2-v4.0.2",
        "status": "FAILED"
      }
    ]
  },
  "fedora-last-latest-x64": {
    "url": "https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=fedora-last-latest-x64/866/",
    "modules": []
  },
  "debian9-64": {
    "url": "https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=debian9-64/866/",
    "modules": []
  },
  "ubuntu1804-64": {
    "url": "https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=ubuntu1804-64/866/",
    "modules": []
  },
  "rhel7-s390x": {
    "url": "https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=rhel7-s390x/866/",
    "modules": []
  },
  "aix71-ppc64": {
    "url": "https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=aix71-ppc64/866/",
    "modules": [
      {
        "name": "through2-v4.0.2",
        "status": "FAILED"
      }
    ]
  },
  "osx1014": {
    "url": "https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=osx1014/866/",
    "modules": []
  },
  "win10-vs2019": {
    "url": "https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=win10-vs2019/866/",
    "modules": [
      {
        "name": "through2-v4.0.2",
        "status": "FAILED"
      }
    ]
  },
  "fedora-latest-x64": {
    "url": "https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=fedora-latest-x64/866/",
    "modules": []
  },
  "centos7-ppcle": {
    "url": "https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=centos7-ppcle/866/",
    "modules": []
  },
  "ubuntu1604-64": {
    "url": "https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=ubuntu1604-64/866/",
    "modules": []
  }
}
```

</details>

<details>
<Summary> Markdown Output </Summary>

```
# CITGM Data for [866](https://ci.nodejs.org/job/citgm-smoker-nobuild/866/)

## Statistics for job [866](https://ci.nodejs.org/job/citgm-smoker-nobuild/866/)

|  FAILED  |  SKIPPED  |  PASSED  |  TOTAL  |
| -------- | --------- | -------- | ------- |
| 3        | 0         | 9        | 12      |

## Failures in job [866](https://ci.nodejs.org/job/citgm-smoker-nobuild/866/)

### [osx1015](https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=osx1015/866/)

None.

### [win2016-vs2017](https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=win2016-vs2017/866/)

* through2-v4.0.2

### [fedora-last-latest-x64](https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=fedora-last-latest-x64/866/)

None.

### [debian9-64](https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=debian9-64/866/)

None.

### [ubuntu1804-64](https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=ubuntu1804-64/866/)

None.

### [rhel7-s390x](https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=rhel7-s390x/866/)

None.

### [aix71-ppc64](https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=aix71-ppc64/866/)

* through2-v4.0.2

### [osx1014](https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=osx1014/866/)

None.

### [win10-vs2019](https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=win10-vs2019/866/)

* through2-v4.0.2

### [fedora-latest-x64](https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=fedora-latest-x64/866/)

None.

### [centos7-ppcle](https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=centos7-ppcle/866/)

None.

### [ubuntu1604-64](https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=ubuntu1604-64/866/)

None.
```

</details>

cc @MylesBorins

### CODE REVIEW

**Comment by codebytere** [comment]
The summary for nobuild jobs is a bit of a downer but i think that probably needs to be fixed on the CI config side instead of on this end.

**Comment by richardlau** [comment]
> 
> 
> The summary for nobuild jobs is a bit of a downer but i think that probably needs to be fixed on the CI config side instead of on this end.

In what respect? FWIW the particular run of the job, https://ci.nodejs.org/job/citgm-smoker-nobuild/866/, specifically only ran tests for the `through2` module (CITGM_COMMAND: `citgm through2` instead of `citgm-all`) and not the entire lookup.

**Comment by codebytere** [comment]
@richardlau this:

Result     FAILURE
URL        https://ci.nodejs.org/job/citgm-smoker-nobuild/866/
Source     
Commit     Unknown
Date       
Author     Unknown
```

I'm not 100% sure why it returns unknown but it's be ideal for it to show the release commit for the last released tarball if possible!

**Comment by richardlau** [comment]
Ah right, yeah the job doesn't know what commit was used. What the job does is scrape the appropriate directory in https://nodejs.org/download/ (e.g. https://nodejs.org/download/release/ when "release" is selected for `DOWNLOAD_LOCATION`) and finds the most recent directory that matches the `NODE_VERSION` field. So for example for `v10` it will pick to download Node.js from https://nodejs.org/download/release/v10.21.0/ and there's nothing AFAIK in that directory or the files within it that indicates what commit was used. 

For releases perhaps node-core-utils could tie them back to tags in the core repo but I don't think we could do that for the rc builds.

**Pull request merged**
