### PR TITLE
ncu-ci: refactor ncu-ci, implement `ncu-ci walk`

### PR DESCRIPTION
**Pull request by joyeecheung**
- Split the failure parsing code into `lib/ci_failure_parser.js`
- Added a test case for infra failure
- Support `--json` to write the results into a JSON
- Skip builds that do not match their upstream (the transparent "skipped" builds in Jenkins)
- Implement `ncu-ci walk` that walk the last 100 runs (that's what we store) of the CI. Combined with `--json` or `--copy` this can write all the failures somewhere for research.

### CODE REVIEW

**Comment by joyeecheung** [comment]
The database of today: https://gist.github.com/joyeecheung/2d189d9cbbfa146827f31716c5837590

**Comment by joyeecheung** [comment]
Also another data that could be useful:

Reasons of CI failure ranked by failed PR count, 2018-06-14
https://gist.github.com/joyeecheung/c40ef984af4b17f6171efa754fddae3b

**Comment by joyeecheung** [comment]
cc @nodejs/automation

**Comment by joyeecheung** [comment]
Pinging @nodejs/automation again for reviews....I'd like to merge this and build the flaky test database idea in https://github.com/nodejs/reliability on top of this PR

**Comment by priyankp10** [comment]
I went through around half of the changes, i'd expect to finish my review today.

**Comment by priyankp10** [comment]
Nice merged, I think the `ncu-ci walk` will be used to collect data for nodejs/reliability?

**Comment by joyeecheung** [comment]
@priyankp10 Yes, I got another PR that generates the a row of the CI health history in https://github.com/nodejs/reliability#ci-health-history . The output of `ncu-ci walk pr --json path/to.json` can be used to generate the [flaky test database](https://github.com/nodejs/reliability/blob/master/flakes.draft.json) (currently lacking `added` and `issues` fields)

**Pull request merged**
