### PR TITLE
fix: use git apply not system apply

### PR DESCRIPTION
**Pull request by codebytere**
Closes https://github.com/nodejs/node-core-utils/issues/421.

Switches to `git apply` vs system `apply`, since the available options for system `apply` differ between systems.

cc @targos

### CODE REVIEW

**Comment by targos** [comment]
There is some regression. For example with this commit: https://github.com/v8/v8/commit/50af61718d49c4f04d0839476c78e3b305d03de4

`git node v8 backport 50af61718d49c4f04d0839476c78e3b305d03de4` succeeds with the current implementation and doesn't work with this PR (it asks to resolve merge conflicts but there are no changed files).

**Comment by codebytere** [comment]
@targos should be fixed up now - working with the supplied commit.

**Comment by targos** [comment]
It broke one of the V8 commands:

https://ci.nodejs.org/job/node-update-v8-canary/1366/display/redirect

```
05:56:25] Commit V8 update [started]
[05:56:25] Commit V8 update [failed]
[05:56:25] → args.unshift is not a function
✖ args.unshift is not a function
```

I'll have a look later if I have time.

**Comment by codebytere** [comment]
@targos ah dang i know what it is - i missed two files when i was grepping. Fix up in a bit.

**Pull request merged**
