### PR TITLE
feat(git-node): add support for the `--gpg-sign` git flag

### PR DESCRIPTION
**Pull request by aduh95**
I've also extended the max line length from 80 to 100 as it was making less readable to keep it at 80 IMO.

### CODE REVIEW

**Comment by targos** [comment]
I personally set this in my gut config. What's the advantage of this flag compared to it ?

**Comment by aduh95** [comment]
The flag let's you select a specific keyid to sign the commit with.

**Comment by targos** [comment]
In the git config you can set ˋuser.signingkey` with the key I'd

**Comment by aduh95** [comment]
If you have set a specific key id in your git config, the flag lets you specify a different one.

**Comment by targos** [comment]
I still don't understand the use case. Don't you always use the same key for the node repo?

**Comment by aduh95** [comment]
No, I usually don't sign my commits for the node repo (why would I, the CQ would sign them for me), but in the rare cases when I need to push manually to `main`, I have to do the `git commit --amend --no-edit -S` dance, and it seems easy to add the flag to ncu instead.

**Review by anonrig — APPROVED** [review]

**Pull request merged**
