### PR TITLE
feat: suggest `gh pr` commands to finish landing

### PR DESCRIPTION
**Pull request by targos**
Also make the output easier to copy and paste.

### CODE REVIEW

**Comment by targos** [comment]
Example output:

```
The following commits are ready to be pushed to upstream/master
- 61a73f80c7 typings: add more bindings typings
--------------------------------------------------------------------------------
Temporary files removed.
To finish landing:
1. Run:
   git push upstream master
2. Post "Landed in 61a73f80c7f9" in https://github.com/nodejs/node/pull/40415
   gh pr comment 40415 --body "Landed in 61a73f80c7f9"
   gh pr close 40415
```

**Review by Trott — APPROVED** [review]
Works for me if we don't think it will confuse folks.

**Comment by aduh95** [comment]
Maybe we can test if `gh` is on the $PATH before printing its commands? It might be confusing for someone who doesn’t know what `gh` is.

**Comment by targos** [comment]
> Maybe we can test if `gh` is on the $PATH before printing its commands? It might be confusing for someone who doesn’t know what `gh` is.

Ok, I'm thinking about using [`which`](https://github.com/npm/node-which#usage) to check whether a `gh` command exists. Do you have a better idea?

**Comment by Trott** [comment]
> > Maybe we can test if `gh` is on the $PATH before printing its commands? It might be confusing for someone who doesn’t know what `gh` is.
> 
> Ok, I'm thinking about using [`which`](https://github.com/npm/node-which#usage) to check whether a `gh` command exists. Do you have a better idea?

For UNIX-like operating systems, maybe [use `command -v` over `which`](https://stackoverflow.com/a/677212/436641), although `which` will certainly work.

For Windows, I guess we'd want to use [`where`](https://stackoverflow.com/a/304447/436641).

**Comment by targos** [comment]
I linked to the `which` npm package, not the Unix command

**Comment by targos** [comment]
Done.

**Review by aduh95 — APPROVED** [review]

**Pull request merged**
